<?php

/**
 * @file
 * News article content type installation file.
 */

use Drupal\block\Entity\Block;
use Drupal\metatag\Entity\MetatagDefaults;
use Drupal\pathauto\Entity\PathautoPattern;
use Drupal\utnews\Permissions;
use Drupal\utnews_content_type_news\Hook\Hooks;
use Drupal\utnews_content_type_news\NewsContentTypeHelper;
use Symfony\Component\Yaml\Yaml;

/**
 * Implements hook_install().
 */
function utnews_content_type_news_install() {
  // Add default Pathauto setting for content type.
  _utnews_add_pathauto_pattern();
  // Add default metatags.
  _utnews_add_metatags();
  // Add social sharing block.
  NewsContentTypeHelper::addSocialSharing();

  // Add standard permissions to "utexas_site_manager" & "utexas_content_editor"
  // if those roles exist.
  Permissions::assignPermissions('editor', 'utexas_content_editor');
  Permissions::assignPermissions('manager', 'utexas_site_manager');

  Hooks::addStandardWorkflow();
}

/**
 * Implements hook_update_dependencies().
 */
function utnews_content_type_news_update_dependencies() {
  // The utnews_content_type_news_update_8109() function provided
  // by this module must run after the utexas_update_8127() function provided by
  // 'utexas' prfile.
  $dependencies['utnews_content_type_news'][8109] = [
    'utexas' => 8127,
  ];
  $dependencies['utnews_content_type_news'][8113] = [
    'utexas' => 8150,
  ];
  return $dependencies;
}

/**
 * Implements hook_uninstall().
 */
function utnews_content_type_news_uninstall() {
  // Delete default metatags.
  _utnews_delete_metatags();
  // Remove social sharing block from Block UI.
  if ($block = Block::load('speedway_addtoany_utexas')) {
    $block->delete();
  }
}

/**
 * Check if a pathauto pattern has a condition for `utnews_news`.
 */
function _utnews_no_existing_pathauto_pattern() {
  $no_profile_pathauto_defined = TRUE;
  // Load all pattern configuration entities.
  foreach (\Drupal::configFactory()->listAll('pathauto.pattern.') as $pattern_config_name) {
    $pattern_config = \Drupal::configFactory()->getEditable($pattern_config_name);
    if ($pattern_config->get('type') == 'canonical_entities:node') {
      $selection_criteria = $pattern_config->get('selection_criteria');
      foreach ($selection_criteria as $uuid => $condition) {
        if ($condition['id'] == 'node_type') {
          $bundles = array_keys($selection_criteria[$uuid]['bundles']);
          if (in_array('utnews_news', $bundles)) {
            $no_profile_pathauto_defined = FALSE;
          }
          break;
        }
      }
    }
  }
  return $no_profile_pathauto_defined;
}

/**
 * Save a pathauto pattern configuration entity.
 */
function _utnews_add_pathauto_pattern() {
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('pathauto')) {
    if (_utnews_no_existing_pathauto_pattern()) {
      $pattern = PathautoPattern::create([
        'id' => 'utnews_news',
        'label' => 'Pathauto : News article content type',
        'type' => 'canonical_entities:node',
        'pattern' => '/news/[node:title]',
        'weight' => _set_news_pattern_weight_before_generic(),
      ]);
      $pattern->addSelectionCondition(
        [
          'id' => 'entity_bundle:node',
          'bundles' => [
            'utnews_news' => 'utnews_news',
          ],
          'negate' => FALSE,
          'context_mapping' => [
            'node' => 'node',
          ],
        ]
      );
      $pattern->save();
    }
  }
}

/**
 * Set metatags for utnews_news content type.
 */
function _utnews_add_metatags() {
  $modules_to_install = [
    'metatag_twitter_cards',
    'metatag_open_graph',
    'schema_metatag',
    'schema_article',
  ];
  foreach ($modules_to_install as $module) {
    if (\Drupal::moduleHandler()->moduleExists($module) === FALSE) {
      \Drupal::service('module_installer')->install([$module]);
    }
  }
  $tags = [
    'title' => '[current-page:title] | [site:name]',
    'description' => '[node:field_utnews_body:summary]',
    'canonical_url' => '[current-page:url]',
    'og_title' => '[current-page:title]',
    'og_description' => '[node:field_utnews_body:summary]',
    'og_image' => '[node:field_utnews_main_media:entity:field_utexas_media_image:utexas_image_style_1140w_616h]',
    'og_url' => '[current-page:url]',
    'twitter_cards_type' => 'summary',
    'schema_article_date_modified' => '[node:changed:html_datetime]',
    'schema_article_type' => 'NewsArticle',
    'schema_article_main_entity_of_page' => '[current-page:url]',
    'schema_article_image' => 'a:4:{s:5:"@type";s:11:"ImageObject";s:3:"url";s:92:"[node:field_utnews_main_media:entity:field_utexas_media_image:utexas_image_style_1140w_616h]";s:5:"width";s:4:"1140";s:6:"height";s:3:"616";}',
    'schema_article_headline' => '[current-page:title]',
    'schema_article_publisher' => 'a:4:{s:5:"@type";s:12:"Organization";s:3:"@id";s:10:"[site:url]";s:4:"name";s:11:"[site:name]";s:3:"url";s:10:"[site:url]";}',
    'schema_article_about' => '[node:field_utnews_news_categories], [node:field_utnews_news_tags]',
    'schema_article_name' => '[current-page:title]',
    'schema_article_description' => '[node:field_utnews_body:summary]',
    'schema_article_date_published' => '[node:field_utnews_publication_date:date:html_datetime]',
    'schema_article_author' => 'a:4:{s:5:"@type";s:6:"Person";s:3:"@id";s:45:"[node:field_utnews_article_author:entity:url]";s:4:"name";s:46:"[node:field_utnews_article_author:entity:name]";s:3:"url";s:45:"[node:field_utnews_article_author:entity:url]";}',
  ];
  $metatag = MetatagDefaults::create([
    'id' => 'node__utnews_news',
    'label' => 'News content type metatags',
    'tags' => $tags,
  ]);
  $metatag->save();
}

/**
 * Delete metatags for utnews_news content type.
 */
function _utnews_delete_metatags() {
  $metatag = MetatagDefaults::load('node__utnews_news');
  $metatag->delete();
}

/**
 * Provide weight that takes presedence over generic pattern.
 *
 * @return string
 *   The weight of the custom pathauto pattern.
 */
function _set_news_pattern_weight_before_generic() {
  // Default to -10 in case there is a generic pattern.
  $weight = -10;
  // If generic pattern present, place it 1 level above.
  if ($generic = PathautoPattern::load('pathauto_node')) {
    $weight = (int) $generic->get('weight') - 1;
  }
  return (string) $weight;
}

/**
 * Have news pattern above fallback content pattern.
 */
function utnews_content_type_news_update_8101() {
  $pattern = PathautoPattern::load('utnews_news');
  $pattern->set('weight', _set_news_pattern_weight_before_generic())->save();
}

/**
 * Import new teaser view mode display (#30).
 */
function utnews_content_type_news_update_8102() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Import updated teaser view mode display & 'featured' checkbox.
 */
function utnews_content_type_news_update_8103() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Use landscape image derivative in teaser (fixes #54).
 */
function utnews_content_type_news_update_8104() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Change metatag twitter_card_type to summary (fixes #109).
 */
function utnews_content_type_news_update_8105() {
  if ($metatag = MetatagDefaults::load('node__utnews_news')) {
    $tag = ['twitter_cards_type' => 'summary'];
    $metatag->overwriteTags($tag);
    $metatag->save();
  }
}

/**
 * Update help text on main image (#51).
 */
function utnews_content_type_news_update_8106() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Add external link to node view (#117).
 */
function utnews_content_type_news_update_8107() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Fix external link help text typo (#141).
 */
function utnews_content_type_news_update_8108() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Relocate Social Sharing block to addtoany_utexas (utdk_profile #1785).
 */
function utnews_content_type_news_update_8109() {
  NewsContentTypeHelper::addSocialSharing();
}

/**
 * HOTFIX: Allow field_utnews_display_image node field to... (#191).
 */
function utnews_content_type_news_update_8110() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Issue #219: Fatal error with Ctools update to 4.0.1 or 3.10.
 *
 * Copy of pathauto update hook 8107.
 *
 * @see https://www.drupal.org/project/pathauto/issues/3222776
 */
function utnews_content_type_news_update_8111() {
  // Load all pattern configuration entities.
  foreach (\Drupal::configFactory()->listAll('pathauto.pattern.') as $pattern_config_name) {
    $pattern_config = \Drupal::configFactory()->getEditable($pattern_config_name);

    // Loop patterns and swap the node_type plugin by the entity_bundle:node
    // plugin.
    if ($pattern_config->get('type') === 'canonical_entities:node') {
      $selection_criteria = $pattern_config->get('selection_criteria');
      foreach ($selection_criteria as $uuid => $condition) {
        if ($condition['id'] === 'node_type') {
          $pattern_config->set("selection_criteria.$uuid.id", 'entity_bundle:node');
          $pattern_config->save();
          break;
        }
      }
    }
  }
}

/**
 * Invalidate existing render cache (#230).
 */
function utnews_content_type_news_update_8112() {
  /** @var \Drupal\Core\Cache\CacheBackendInterface $render_cache */
  $render_cache = \Drupal::service('cache.render');
  $render_cache->deleteAll();
}

/**
 * Use "Standard workflow" on News nodes #271.
 */
function utnews_content_type_news_update_8113() {
  Hooks::addStandardWorkflow();
}

/**
 * Issue #233: Convert News teaser variations to separate view modes.
 */
function utnews_content_type_news_update_8114() {
  \Drupal::service('features.manager')->import([
    'utnews_content_type_news',
  ], TRUE);
}

/**
 * Update teaser view mode to render only title (#3300).
 */
function utnews_content_type_news_update_8115() {
  $module_handler = \Drupal::service('module_handler');
  $module_path = $module_handler->getModule('utnews_content_type_news')->getPath();
  $config = 'core.entity_view_display.node.utnews_news.teaser';
  $config_path = $module_path . '/config/install/' . $config . '.yml';
  $data = Yaml::parse(file_get_contents($config_path));
  \Drupal::configFactory()->getEditable($config)->setData($data)->save();
}
