<?php

/**
 * @file
 * Contains install and update functions for Profile listings.
 */

use Drupal\utexas_layout_builder_styles\StyleUpdateHelper;
use Drupal\utprof_block_type_profile_listing\ProfileListingHelper;

/**
 * Implements hook_install().
 */
function utprof_block_type_profile_listing_install() {
  // Allow Profile Listings for 1, 2, 3, and 4 column Layout Builder Styles.
  _utprof_block_type_profile_listing_block_restriction_add();
}

/**
 * Implements hook_uninstall().
 */
function utprof_block_type_profile_listing_uninstall() {
  // Disallow Profile Listings for 1, 2, 3, and 4 column Layout Builder Styles.
  _utprof_block_type_profile_listing_block_restriction_remove();
}

/**
 * Helper function to add block to Layout Builder Styles.
 */
function _utprof_block_type_profile_listing_block_restriction_add() {
  $layout_builder_styles = [
    'layout_builder_styles.style.utexas_onecol',
    'layout_builder_styles.style.utexas_twocol',
    'layout_builder_styles.style.utexas_threecol',
    'layout_builder_styles.style.utexas_fourcol',
  ];
  foreach ($layout_builder_styles as $layout_builder_style) {
    StyleUpdateHelper::modifyConfigValue($layout_builder_style, 'block_restrictions', 'inline_block:utprof_profile_listing');
  }
}

/**
 * Helper function to remove block from Layout Builder Styles.
 */
function _utprof_block_type_profile_listing_block_restriction_remove() {
  $layout_builder_styles = [
    'layout_builder_styles.style.utexas_onecol',
    'layout_builder_styles.style.utexas_twocol',
    'layout_builder_styles.style.utexas_threecol',
    'layout_builder_styles.style.utexas_fourcol',
  ];
  foreach ($layout_builder_styles as $layout_builer_style) {
    StyleUpdateHelper::removeConfigArrayValue($layout_builer_style, 'block_restrictions', 'inline_block:utprof_profile_listing');
  }
}

/**
 * Repurpose field as 'Internal Profile tags'.
 */
function utprof_block_type_profile_listing_update_8101() {
  \Drupal::service('features.manager')->import([
    'utprof_block_type_profile_listing',
  ], TRUE);
}

/**
 * Update documentation link for default display types.
 */
function utprof_block_type_profile_listing_update_8102() {
  \Drupal::service('features.manager')->import([
    'utprof_block_type_profile_listing',
  ], TRUE);
}

/**
 * Issue #208 : Make 1-4 items per row available for existing Profile Lists.
 */
function utprof_block_type_profile_listing_update_8103() {
  // Allow Profile Listings for 1, 2, 3, and 4 column Layout Builder Styles.
  _utprof_block_type_profile_listing_block_restriction_add();
}

/**
 * Issue #208 : Update LBSs in existing Profile Listing blocks using view modes.
 */
function utprof_block_type_profile_listing_update_8104() {
  $style_map = [
    'utexas_basic' => 'utexas_twocol',
    'utexas_name_only' => 'utexas_twocol',
    'utexas_prominent' => 'utexas_onecol',
  ];

  ProfileListingHelper::mapViewModeToStyle('utprof_profile_listing', $style_map);
}

/**
 * Add ability to create listings of specific profiles w/arbitrary order (#188).
 */
function utprof_block_type_profile_listing_update_8105() {
  \Drupal::service('features.manager')->import([
    'utprof_block_type_profile_listing',
  ], TRUE);
}

/**
 * Convert field_utprof_view_mode default value callback to OOP (#449).
 */
function utprof_block_type_profile_listing_update_8106() {
  $config = \Drupal::configFactory()->getEditable('field.field.block_content.utprof_profile_listing.field_utprof_view_mode');
  if ($config->get('default_value_callback') === 'utprof_block_type_profile_listing_view_mode_default_value') {
    $config->set('default_value_callback', 'Drupal\utprof_block_type_profile_listing\Hook\Hooks::viewModeDefaultValue');
    $config->save();
  }
}
