<?php

/**
 * @file
 * Contains install and update functions for the UTexas Reources module.
 */

use Drupal\Core\Database\Database;

/**
 * Issue #1029: Support custom link options in Resources links.
 */
function utexas_resources_update_8101() {
  // Update 'url' value keys to 'uri' in the blob field. MySQL auto-converts it
  // back to blob on execute ("save").
  $database_connection = Database::getConnection();
  $query = $database_connection->query(
    "SELECT value FROM {key_value} WHERE name=:name",
    [
      ':name' => "block_content.field_schema_data.field_block_resources",
    ]
  );
  $result = $query->fetchAssoc();
  $fh_tables = array_keys(unserialize($result['value']));

  foreach ($fh_tables as $table_name) {
    $field_name = 'field_block_resources_resource_items';
    $old_value = '"url";';
    $new_value = '"uri";';
    $database_connection->update($table_name)
      // ->condition($field_name, $old_value, 'LIKE')
      ->expression($field_name, 'replace(CONVERT(' . $field_name . ' USING utf8), :old, :new)', [
        ':old' => $old_value,
        ':new' => $new_value,
      ])
      ->execute();
  }

}

/**
 * Set field storage configuration to 'locked' (#1548).
 */
function utexas_resources_update_8102() {
  \Drupal::service('features.manager')->import([
    'utexas_resources',
  ], TRUE);
}
